### ISSUE TITLE
VAC 패턴에 기반한 Todo 기능 구현

### ISSUE THREAD

**Issue by herekim** [herekim/yp-todo-rn#3]
# 이슈 설명
- VAC 패턴에 대한 이해를 선행하고, 이를 바탕으로 요구 사항 반영
# 태스크
- [x] Todo Item 작성하기
  - [x] Item 내용이 공백일 경우, Todo 작성 불가능
  - [x] Todo를 작성하는 부분은 모달로 구현
- [x] Todo Item 삭제하기
- [x] Todo Item 수정하기
  - [x] 수정된 Item 내용이 공백일 경우, 수정 완료가 불가능
  - [x] Todo Item 수정과 작성의 모달은 UI 통일성
- [x] Todo Item 토글 방식으로 완료 & 완료 취소
  - [x] 토글된 값 저장, 앱 닫았다가 열어도 토글 상태 저장
  - [x] 완료된 Todo는 수정 불가능
- [x] Todo Item 클릭 시 상세 보기 페이지로 전환
  - [x] 상세 보기 페이지에서 완료 & 완료 수정
  - [x] 상세 보기 페이지에서 수정 가능
- [x] Todo Item의 내용이 5줄 이상 넘어갈 시 ellipsis 표시
- [x] 화면 아래로 당겨 새로 고침
  - [x] 새로 고침 사용 시 최신 10개의 Todo Item 보이도록 구현
- [x] 새로운 Todo Item 생성할 때마다, 만들어진 Todo Item은 가장 상단에 위치
- [x] 무한 스크롤 구현
  - [x] 화면 진입 시 10개의 Todo Item 호출, 화면 하단 도달 시 10개의 추가 Todo Item 호출
# 기타
- VAC 패턴을 기반으로 Props를 객체로 묶어서 보내는 부분 중요
